host: 0.0.0.0
description: Monine 的个人博客
url: "https://znlbwo.github.io"
author: Enihvup.Znlbwo
lang: zh-cmn-Hans

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
